
version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - SECRET_KEY= ${SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  postgres_data:


